---
- name: UPGRADE ALL INSTALLED PACKAGES
  hosts: '{{ tower_inventory }}'
  gather_facts: false
  become: true
  
  tasks:
    - name: UPGRADE ALL PACKAGES
      yum:
        name: '*'
        state: latest
          